// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL2mV1A4OKU2rwQ42fonqqrEnQiDRcsIk',
    appId: '1:856085266304:web:bf6c7509be319a40154b65',
    messagingSenderId: '856085266304',
    projectId: 'mobikadproject',
    authDomain: 'mobikadproject.firebaseapp.com',
    storageBucket: 'mobikadproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoMn0U5zjKGjNWd9Za8oy0Pqs7sWm5Dkc',
    appId: '1:856085266304:android:47f60dddb692dc06154b65',
    messagingSenderId: '856085266304',
    projectId: 'mobikadproject',
    storageBucket: 'mobikadproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYoR08q8ZIdKjWSIvEsav433DXLi1hAWY',
    appId: '1:856085266304:ios:10e5b3b458d3b4c4154b65',
    messagingSenderId: '856085266304',
    projectId: 'mobikadproject',
    storageBucket: 'mobikadproject.firebasestorage.app',
    iosBundleId: 'com.example.mobikad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYoR08q8ZIdKjWSIvEsav433DXLi1hAWY',
    appId: '1:856085266304:ios:10e5b3b458d3b4c4154b65',
    messagingSenderId: '856085266304',
    projectId: 'mobikadproject',
    storageBucket: 'mobikadproject.firebasestorage.app',
    iosBundleId: 'com.example.mobikad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL2mV1A4OKU2rwQ42fonqqrEnQiDRcsIk',
    appId: '1:856085266304:web:61465ee9fc181312154b65',
    messagingSenderId: '856085266304',
    projectId: 'mobikadproject',
    authDomain: 'mobikadproject.firebaseapp.com',
    storageBucket: 'mobikadproject.firebasestorage.app',
  );
}
